# Generated by Django 2.1.5 on 2019-03-15 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0002_auto_20190315_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date_published'),
        ),
    ]
