# Generated by Django 2.1.5 on 2019-03-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0007_auto_20190317_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='address_one',
            field=models.CharField(default=5, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='address_two',
            field=models.CharField(default=5, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='post_code',
            field=models.CharField(default=3, max_length=8),
            preserve_default=False,
        ),
    ]
