# Generated by Django 2.1.5 on 2019-03-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0008_auto_20190317_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='like',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
