# Generated by Django 2.1.5 on 2019-03-27 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0016_auto_20190327_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
    ]
