# Generated by Django 2.1.5 on 2019-03-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0018_auto_20190327_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
