# Generated by Django 2.1.5 on 2019-04-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0021_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='profile_photos/None/no-img.png', upload_to='profile_photos'),
        ),
    ]
