# Generated by Django 2.1.5 on 2019-04-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0022_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='profile_photos/None/no-img.png', upload_to='media'),
        ),
    ]
