# Generated by Django 2.1.5 on 2019-04-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0023_auto_20190405_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='profile_photos/no-img.png', upload_to='media'),
        ),
    ]
