# Generated by Django 2.1.5 on 2019-04-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0024_auto_20190424_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
