# Generated by Django 2.1.5 on 2019-04-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0025_auto_20190424_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.TextField(max_length=500),
        ),
    ]
