# Generated by Django 2.1.5 on 2019-04-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0026_auto_20190424_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('class_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
