# Generated by Django 2.1.5 on 2019-04-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0027_elements'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Dublin', max_length=25),
            preserve_default=False,
        ),
    ]
