# Generated by Django 2.1.5 on 2019-04-26 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0028_profile_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Elements',
        ),
    ]
