# Generated by Django 2.1.5 on 2019-04-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0030_auto_20190426_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
